/** Jar SSOT: allure-notifications-api/src/main/resources/phrases/*.json */
export const PHRASES = Object.freeze({
    en: {
        results: 'Results',
        environment: 'Environment',
        comment: 'Comment',
        links: {
            report: 'Report',
            dashboard: 'Dashboard',
            testops: 'TestOps',
            build: 'Build',
        },
        scenario: {
            duration: 'Duration',
            totalScenarios: 'Total scenarios',
            totalPassed: 'Total passed',
            totalFailed: 'Total failed',
            totalBroken: 'Total broken',
            totalUnknown: 'Total unknown',
            totalSkipped: 'Total skipped',
        },
    },
    ru: {
        results: 'Результаты',
        environment: 'Рабочее окружение',
        comment: 'Комментарий',
        links: {
            report: 'Отчёт',
            dashboard: 'Дашборд',
            testops: 'TestOps',
            build: 'Сборка',
        },
        scenario: {
            duration: 'Продолжительность',
            totalScenarios: 'Всего сценариев',
            totalPassed: 'Всего успешных тестов',
            totalFailed: 'Всего упавших тестов',
            totalBroken: 'Всего сломанных тестов',
            totalUnknown: 'Всего неизвестных тестов',
            totalSkipped: 'Всего пропущенных тестов',
        },
    },
    fr: {
        results: 'Résultats',
        environment: 'Environnement',
        comment: 'Commentaire',
        links: {
            report: 'Rapport',
            dashboard: 'Tableau de bord',
            testops: 'TestOps',
            build: 'Build',
        },
        scenario: {
            duration: 'Durée',
            totalScenarios: 'Scénarios totaux',
            totalPassed: 'Total passé',
            totalFailed: 'Total a échoué',
            totalBroken: 'Total cassé',
            totalUnknown: 'Total inconnu',
            totalSkipped: 'Total ignoré',
        },
    },
    ua: {
        results: 'Результати',
        environment: 'Середовище',
        comment: 'Коментар',
        links: {
            report: 'Звіт',
            dashboard: 'Дашборд',
            testops: 'TestOps',
            build: 'Збірка',
        },
        scenario: {
            duration: 'Тривалість',
            totalScenarios: 'Усього сценаріїв',
            totalPassed: 'Усього успішних тестів',
            totalFailed: 'Усього невдалих тестів',
            totalBroken: 'Усього зламаних тестів',
            totalUnknown: 'Усього невідомих тестів',
            totalSkipped: 'Всього пропущених тестів',
        },
    },
    by: {
        results: 'Вынікі',
        environment: 'Працоўнае асяроддзе',
        comment: 'Каментар',
        links: {
            report: 'Справаздача',
            dashboard: 'Дашборд',
            testops: 'TestOps',
            build: 'Зборка',
        },
        scenario: {
            duration: 'Працягласць',
            totalScenarios: 'Усяго сцэнарыяў',
            totalPassed: 'Усяго паспяховых тэстаў',
            totalFailed: 'Усяго тэстаў, якія ўпалі',
            totalBroken: 'Усяго зламаных тэстаў',
            totalUnknown: 'Усяго невядомых тэстаў',
            totalSkipped: 'Усяго прапушчаных тэстаў',
        },
    },
    cn: {
        results: '测试结果',
        environment: '环境',
        comment: '评论',
        links: {
            report: '报告',
            dashboard: '仪表盘',
            testops: 'TestOps',
            build: '构建',
        },
        scenario: {
            duration: '持续时间',
            totalScenarios: '脚本总数',
            totalPassed: '通过总数',
            totalFailed: '失败总数',
            totalBroken: '损坏总数',
            totalUnknown: '未知错误总数',
            totalSkipped: '跳过总数',
        },
    },
    cnt: {
        results: '測試結果',
        environment: '環境',
        comment: '评论',
        links: {
            report: '報告',
            dashboard: '儀表盤',
            testops: 'TestOps',
            build: '構建',
        },
        scenario: {
            duration: '持續時間',
            totalScenarios: '腳本總數',
            totalPassed: '通過總數',
            totalFailed: '失敗總數',
            totalBroken: '損壞總數',
            totalUnknown: '未知錯誤總數',
            totalSkipped: '跳過總數',
        },
    },
});
