/**
 * Emit sw.js for the static builder (GH Pages) per design-system PWA contract:
 * skipWaiting, clientsClaim, cleanupOutdatedCaches, navigateFallback index.html.
 *
 * Usage: node scripts/generate-sw.mjs
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const builderRoot = fileURLToPath(new URL('..', import.meta.url));

const GLOB_ROOTS = [
  'index.html',
  'manifest.webmanifest',
  'css',
  'js',
  'icons',
  'vendor',
];

/** @param {string} dir */
function walk(dir) {
  /** @type {string[]} */
  const out = [];
  for (const name of readdirSync(dir)) {
    if (name === 'node_modules' || name === 'test-results' || name === 'playwright-report') {
      continue;
    }
    const full = join(dir, name);
    const st = statSync(full);
    if (st.isDirectory()) {
      out.push(...walk(full));
    } else if (/\.(html|js|css|png|svg|webmanifest|ico|woff2?)$/i.test(name)) {
      out.push(full);
    }
  }
  return out;
}

/** @type {string[]} */
const files = [];
for (const root of GLOB_ROOTS) {
  const full = join(builderRoot, root);
  try {
    const st = statSync(full);
    if (st.isDirectory()) {
      files.push(...walk(full));
    } else if (st.isFile()) {
      files.push(full);
    }
  } catch {
    // optional path
  }
}

const precache = files
  .map((abs) => {
    const url = '/' + relative(builderRoot, abs).split('\\').join('/');
    const revision = createHash('md5').update(readFileSync(abs)).digest('hex').slice(0, 16);
    return { url, revision };
  })
  .sort((a, b) => a.url.localeCompare(b.url));

const sw = `/* generated by scripts/generate-sw.mjs — do not edit */
const PRECACHE = 'anb-shell';
const MANIFEST = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(PRECACHE).then((cache) =>
      Promise.all(
        MANIFEST.map(({ url, revision }) =>
          cache.put(
            url,
            fetch(url).then(async (res) => {
              if (!res.ok) throw new Error('precache failed ' + url);
              const headers = new Headers(res.headers);
              headers.set('x-anb-rev', revision);
              return new Response(await res.blob(), { status: res.status, statusText: res.statusText, headers });
            }),
          ),
        ),
      ),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== PRECACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('/index.html').then((cached) => cached || fetch(request)),
    );
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(url.pathname).then((cached) => cached || fetch(request)),
  );
});
`;

writeFileSync(join(builderRoot, 'sw.js'), sw);
console.log(`generate-sw: ${precache.length} urls → sw.js`);
