/**
 * Phase 4: copy @qa-guru/allure-notifications-config browser surface into vendor/.
 * Needed because python http.server (stand :3011) cannot follow pnpm symlinks
 * outside apps/builder — so bare node_modules/@qa-guru/allure-notifications-config 404s.
 *
 * Usage: node scripts/sync-config.mjs
 * (builds packages/config first)
 */
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const here = dirname(fileURLToPath(import.meta.url));
const builderRoot = join(here, "..");
const workspaceRoot = join(builderRoot, "../..");
const distSrc = join(workspaceRoot, "packages/config/dist/src");
const outDir = join(builderRoot, "vendor/allure-notifications-config");

const build = spawnSync(
  "pnpm",
  ["--filter", "@qa-guru/allure-notifications-config", "run", "build"],
  { cwd: workspaceRoot, stdio: "inherit", shell: process.platform === "win32" },
);
if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

mkdirSync(outDir, { recursive: true });
const files = ["browser.js", "catalog.js", "presets.js", "phrases.js", "kit-only.js"];
for (const name of files) {
  const src = join(distSrc, name);
  // Drop sourceMappingURL — maps are not vendored (stand has no .map files).
  const body = readFileSync(src, "utf8").replace(/\n\/\/# sourceMappingURL=.*$/m, "\n");
  writeFileSync(join(outDir, name), body);
}

writeFileSync(
  join(outDir, "package.json"),
  `${JSON.stringify({ type: "module", private: true }, null, 2)}\n`,
);
writeFileSync(
  join(outDir, "README.md"),
  [
    "# vendor/allure-notifications-config",
    "",
    "Generated by `scripts/sync-config.mjs` from `@qa-guru/allure-notifications-config` (`./browser`).",
    "Do not edit by hand — re-run sync after catalog/presets changes.",
    "",
  ].join("\n"),
);

console.log(`synced ${files.length} files → vendor/allure-notifications-config/`);
