/* generated by scripts/generate-sw.mjs — do not edit */
const PRECACHE = 'anb-shell';
const MANIFEST = [
  {
    "url": "/css/app.css",
    "revision": "16c2fe9d74eb2537"
  },
  {
    "url": "/icons/pwa-192.png",
    "revision": "05d6c56a2fbfb417"
  },
  {
    "url": "/icons/pwa-512.png",
    "revision": "5187f0c71a08df59"
  },
  {
    "url": "/icons/pwa-maskable-512.png",
    "revision": "5187f0c71a08df59"
  },
  {
    "url": "/index.html",
    "revision": "af68ee38ec2924a4"
  },
  {
    "url": "/js/app.js",
    "revision": "bc62a5d8787687d0"
  },
  {
    "url": "/js/phrases.js",
    "revision": "7a6ecd0d2fcdbf4d"
  },
  {
    "url": "/manifest.webmanifest",
    "revision": "b2c8b2259cb27de8"
  },
  {
    "url": "/vendor/allure-notifications-config/browser.js",
    "revision": "d0b0819a7e8a0f4c"
  },
  {
    "url": "/vendor/allure-notifications-config/catalog.js",
    "revision": "9714f1a7e06ee2a8"
  },
  {
    "url": "/vendor/allure-notifications-config/kit-only.js",
    "revision": "55431d1225ee2163"
  },
  {
    "url": "/vendor/allure-notifications-config/phrases.js",
    "revision": "4cc9deed24797bb3"
  },
  {
    "url": "/vendor/allure-notifications-config/presets.js",
    "revision": "bd4ce48144ee7fee"
  },
  {
    "url": "/vendor/allure-notifications-pyramid/browser.js",
    "revision": "d4a26fdc98a7ce18"
  },
  {
    "url": "/vendor/allure-notifications-pyramid/geometry.js",
    "revision": "f3f3a4e90b5df732"
  },
  {
    "url": "/vendor/allure-notifications-pyramid/palette.js",
    "revision": "7291f2fa57d15316"
  },
  {
    "url": "/vendor/design-system/assets/allure3-logo.svg",
    "revision": "4075b2faae1ad2e0"
  },
  {
    "url": "/vendor/design-system/assets/qa-guru-logo.svg",
    "revision": "7503122a5250d584"
  },
  {
    "url": "/vendor/design-system/css/badge.css",
    "revision": "fc54b2c74d9868fc"
  },
  {
    "url": "/vendor/design-system/css/button.css",
    "revision": "82dbea530249cda6"
  },
  {
    "url": "/vendor/design-system/css/code-highlight.css",
    "revision": "8759188e4dbd9e33"
  },
  {
    "url": "/vendor/design-system/css/configurator.css",
    "revision": "934b09e981ad2790"
  },
  {
    "url": "/vendor/design-system/css/grid.css",
    "revision": "2e5bee4d3d1ae9d2"
  },
  {
    "url": "/vendor/design-system/css/header.css",
    "revision": "aa303f8ed343d160"
  },
  {
    "url": "/vendor/design-system/css/icon-btn.css",
    "revision": "6698d905cab2daaf"
  },
  {
    "url": "/vendor/design-system/css/icon.css",
    "revision": "c957058ec21dcc1a"
  },
  {
    "url": "/vendor/design-system/css/indicator.css",
    "revision": "4ce7b7791f8ddb6f"
  },
  {
    "url": "/vendor/design-system/css/input.css",
    "revision": "19b0d5e33d15049a"
  },
  {
    "url": "/vendor/design-system/css/lang-toggle.css",
    "revision": "6a3281b2c4b5d5fa"
  },
  {
    "url": "/vendor/design-system/css/link.css",
    "revision": "b212d39f959f5abe"
  },
  {
    "url": "/vendor/design-system/css/page.css",
    "revision": "0924722b37946a74"
  },
  {
    "url": "/vendor/design-system/css/panel.css",
    "revision": "440abaf2e6415092"
  },
  {
    "url": "/vendor/design-system/css/plaque-divider.css",
    "revision": "e91dcca63e1ae6ae"
  },
  {
    "url": "/vendor/design-system/css/plaque-field-seg-layout.css",
    "revision": "bff9b5553447173c"
  },
  {
    "url": "/vendor/design-system/css/plaque-field-seg.css",
    "revision": "61b7f9939299cc4d"
  },
  {
    "url": "/vendor/design-system/css/plaque-field.css",
    "revision": "243dbcec18205eb3"
  },
  {
    "url": "/vendor/design-system/css/plaque-number.css",
    "revision": "bd90607d1bc2ec12"
  },
  {
    "url": "/vendor/design-system/css/qg-info.css",
    "revision": "4390159da7672f6c"
  },
  {
    "url": "/vendor/design-system/css/quality-gate.css",
    "revision": "e0fbf0fda4323cc3"
  },
  {
    "url": "/vendor/design-system/css/sparkline.css",
    "revision": "934db011899702a4"
  },
  {
    "url": "/vendor/design-system/css/stability-cell.css",
    "revision": "e38d20525ee675b4"
  },
  {
    "url": "/vendor/design-system/css/stack.css",
    "revision": "9cfb470a3e1b4c3e"
  },
  {
    "url": "/vendor/design-system/css/sticky.css",
    "revision": "fd1818fff8d54383"
  },
  {
    "url": "/vendor/design-system/css/tests-table-panel.css",
    "revision": "3ad21fb01c0e4b03"
  },
  {
    "url": "/vendor/design-system/css/text.css",
    "revision": "075dd8694fea5bac"
  },
  {
    "url": "/vendor/design-system/css/tokens.css",
    "revision": "cafeb95c19e6e7d1"
  },
  {
    "url": "/vendor/design-system/css/widget-tile.css",
    "revision": "1f63177c7dfd51a0"
  },
  {
    "url": "/vendor/design-system/js/code-highlight.js",
    "revision": "b99a1f77ebc1ea20"
  },
  {
    "url": "/vendor/design-system/js/dom-utils.js",
    "revision": "a8dfc6000e13b65c"
  },
  {
    "url": "/vendor/design-system/js/header-metrics-wrap.js",
    "revision": "3cf690f6a2835591"
  },
  {
    "url": "/vendor/design-system/js/header.js",
    "revision": "bd2abcf18f4ae10b"
  },
  {
    "url": "/vendor/design-system/js/plaque-number.js",
    "revision": "7c29eb8daeb00015"
  },
  {
    "url": "/vendor/design-system/js/pwa-register.js",
    "revision": "ea7a3123deb6ce08"
  },
  {
    "url": "/vendor/design-system/js/theme-icons.js",
    "revision": "cf340b4aa881c222"
  },
  {
    "url": "/vendor/design-system/js/widget-tile-mocks.js",
    "revision": "dd27cc8f9277106d"
  },
  {
    "url": "/vendor/design-system/templates/header.html",
    "revision": "6b0f364e27b3afff"
  },
  {
    "url": "/vendor/design-system/templates/widget-tile.html",
    "revision": "c71a209992231b27"
  }
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(PRECACHE).then((cache) =>
      Promise.all(
        MANIFEST.map(({ url, revision }) =>
          cache.put(
            url,
            fetch(url).then(async (res) => {
              if (!res.ok) throw new Error('precache failed ' + url);
              const headers = new Headers(res.headers);
              headers.set('x-anb-rev', revision);
              return new Response(await res.blob(), { status: res.status, statusText: res.statusText, headers });
            }),
          ),
        ),
      ),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== PRECACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('/index.html').then((cached) => cached || fetch(request)),
    );
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(url.pathname).then((cached) => cached || fetch(request)),
  );
});
