/* generated by scripts/generate-sw.mjs — do not edit */
const PRECACHE = 'anb-shell';
const MANIFEST = [
  {
    "url": "/css/app.css",
    "revision": "c3d9b114bb8a87aa"
  },
  {
    "url": "/icons/pwa-192.png",
    "revision": "05d6c56a2fbfb417"
  },
  {
    "url": "/icons/pwa-512.png",
    "revision": "5187f0c71a08df59"
  },
  {
    "url": "/icons/pwa-maskable-512.png",
    "revision": "5187f0c71a08df59"
  },
  {
    "url": "/index.html",
    "revision": "7499553b86f4f1cb"
  },
  {
    "url": "/js/app.js",
    "revision": "7b5ed9e3e9027444"
  },
  {
    "url": "/js/grid-editor.js",
    "revision": "4b4896e4109bf1ad"
  },
  {
    "url": "/js/mocks/kit.js",
    "revision": "0e15745a495a2b51"
  },
  {
    "url": "/js/mocks/stock.js",
    "revision": "d998e1d7f800699e"
  },
  {
    "url": "/js/phrases.js",
    "revision": "7326cdcf6b10d442"
  },
  {
    "url": "/js/state.js",
    "revision": "d3ac1f66b8111cdc"
  },
  {
    "url": "/js/tests-table-mock.js",
    "revision": "58be4ec78ae793be"
  },
  {
    "url": "/js/tg-caption.js",
    "revision": "324967e3100d8655"
  },
  {
    "url": "/js/vector-registry.js",
    "revision": "f64c215120848729"
  },
  {
    "url": "/manifest.webmanifest",
    "revision": "a9f284e02e1f0124"
  },
  {
    "url": "/vendor/allure-notifications-config/browser.js",
    "revision": "d0b0819a7e8a0f4c"
  },
  {
    "url": "/vendor/allure-notifications-config/catalog.js",
    "revision": "9714f1a7e06ee2a8"
  },
  {
    "url": "/vendor/allure-notifications-config/kit-only.js",
    "revision": "55431d1225ee2163"
  },
  {
    "url": "/vendor/allure-notifications-config/phrases.js",
    "revision": "7fa31dba8d14651f"
  },
  {
    "url": "/vendor/allure-notifications-config/presets.js",
    "revision": "70df4cb7fa5a3077"
  },
  {
    "url": "/vendor/allure-report-kit-collage/collage-palette.js",
    "revision": "6ac9fce5a7a348a8"
  },
  {
    "url": "/vendor/allure-report-kit-collage/collage.js",
    "revision": "bba87e89a0ba2c58"
  },
  {
    "url": "/vendor/allure-report-kit-collage/testing-pyramid-geometry.js",
    "revision": "c6a31807545fad7f"
  },
  {
    "url": "/vendor/design-system/assets/allure3-logo.svg",
    "revision": "4075b2faae1ad2e0"
  },
  {
    "url": "/vendor/design-system/assets/qa-guru-logo.svg",
    "revision": "095581dc212e9a5d"
  },
  {
    "url": "/vendor/design-system/css/badge.css",
    "revision": "d283dcc5d0adcf32"
  },
  {
    "url": "/vendor/design-system/css/button.css",
    "revision": "82dbea530249cda6"
  },
  {
    "url": "/vendor/design-system/css/code-highlight.css",
    "revision": "0c6ac54bb43034a1"
  },
  {
    "url": "/vendor/design-system/css/configurator.css",
    "revision": "77dfb2672f5643d6"
  },
  {
    "url": "/vendor/design-system/css/grid.css",
    "revision": "2e5bee4d3d1ae9d2"
  },
  {
    "url": "/vendor/design-system/css/header.css",
    "revision": "95e6f6302bc16d9a"
  },
  {
    "url": "/vendor/design-system/css/icon-btn.css",
    "revision": "6b84003fd997aa1a"
  },
  {
    "url": "/vendor/design-system/css/icon.css",
    "revision": "c957058ec21dcc1a"
  },
  {
    "url": "/vendor/design-system/css/indicator.css",
    "revision": "4ce7b7791f8ddb6f"
  },
  {
    "url": "/vendor/design-system/css/input.css",
    "revision": "19b0d5e33d15049a"
  },
  {
    "url": "/vendor/design-system/css/lang-toggle.css",
    "revision": "6a3281b2c4b5d5fa"
  },
  {
    "url": "/vendor/design-system/css/link.css",
    "revision": "2abee6403da9bd74"
  },
  {
    "url": "/vendor/design-system/css/page.css",
    "revision": "2d20c78e4a24373e"
  },
  {
    "url": "/vendor/design-system/css/panel.css",
    "revision": "4e217eaad30d0dd4"
  },
  {
    "url": "/vendor/design-system/css/plaque-divider.css",
    "revision": "e91dcca63e1ae6ae"
  },
  {
    "url": "/vendor/design-system/css/plaque-field-seg-layout.css",
    "revision": "4601c57ad4cc2002"
  },
  {
    "url": "/vendor/design-system/css/plaque-field-seg.css",
    "revision": "2715a5c47ea1d1dc"
  },
  {
    "url": "/vendor/design-system/css/plaque-field.css",
    "revision": "f938354922735a7d"
  },
  {
    "url": "/vendor/design-system/css/plaque-number.css",
    "revision": "bd90607d1bc2ec12"
  },
  {
    "url": "/vendor/design-system/css/qg-info.css",
    "revision": "7e452307337a8df6"
  },
  {
    "url": "/vendor/design-system/css/quality-gate.css",
    "revision": "bcbc0de8c4d7b004"
  },
  {
    "url": "/vendor/design-system/css/sparkline.css",
    "revision": "9fb5a716451b28cb"
  },
  {
    "url": "/vendor/design-system/css/stability-cell.css",
    "revision": "e38d20525ee675b4"
  },
  {
    "url": "/vendor/design-system/css/stack.css",
    "revision": "9cfb470a3e1b4c3e"
  },
  {
    "url": "/vendor/design-system/css/status.css",
    "revision": "e4ebead6a76391b4"
  },
  {
    "url": "/vendor/design-system/css/sticky.css",
    "revision": "7dadbcaba8a57aed"
  },
  {
    "url": "/vendor/design-system/css/tests-table-panel.css",
    "revision": "d6ca9252a1869246"
  },
  {
    "url": "/vendor/design-system/css/text.css",
    "revision": "075dd8694fea5bac"
  },
  {
    "url": "/vendor/design-system/css/tokens.css",
    "revision": "6c771de8bfda4ff8"
  },
  {
    "url": "/vendor/design-system/css/widget-tile.css",
    "revision": "1f63177c7dfd51a0"
  },
  {
    "url": "/vendor/design-system/js/code-highlight.js",
    "revision": "fa2f7c157218e9ee"
  },
  {
    "url": "/vendor/design-system/js/dom-utils.js",
    "revision": "a8dfc6000e13b65c"
  },
  {
    "url": "/vendor/design-system/js/header-metrics-wrap.js",
    "revision": "3cf690f6a2835591"
  },
  {
    "url": "/vendor/design-system/js/header.js",
    "revision": "c8c7914a876e1253"
  },
  {
    "url": "/vendor/design-system/js/plaque-number.js",
    "revision": "7c29eb8daeb00015"
  },
  {
    "url": "/vendor/design-system/js/pwa-register.js",
    "revision": "2bde45f41a229c16"
  },
  {
    "url": "/vendor/design-system/js/theme-icons.js",
    "revision": "cf340b4aa881c222"
  },
  {
    "url": "/vendor/design-system/js/widget-tile-mocks.js",
    "revision": "8a7b52f78cc1a298"
  },
  {
    "url": "/vendor/design-system/templates/header.html",
    "revision": "fb0a8e8a45f3b36e"
  },
  {
    "url": "/vendor/design-system/templates/widget-tile.html",
    "revision": "c71a209992231b27"
  }
];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(PRECACHE).then((cache) =>
      Promise.all(
        MANIFEST.map(({ url, revision }) =>
          cache.put(
            url,
            fetch(url).then(async (res) => {
              if (!res.ok) throw new Error('precache failed ' + url);
              const headers = new Headers(res.headers);
              headers.set('x-anb-rev', revision);
              return new Response(await res.blob(), { status: res.status, statusText: res.statusText, headers });
            }),
          ),
        ),
      ),
    ),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== PRECACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('/index.html').then((cached) => cached || fetch(request)),
    );
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(url.pathname).then((cached) => cached || fetch(request)),
  );
});
